// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDelivery = "delivery"

// Delivery mapped from table <delivery>
type Delivery struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID   int32     `gorm:"column:order_id;not null" json:"order_id"`
	UserID    int32     `gorm:"column:user_id;not null" json:"user_id"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Delivery's table name
func (*Delivery) TableName() string {
	return TableNameDelivery
}
