// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "order"

// Order mapped from table <order>
type Order struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderDate       time.Time `gorm:"column:order_date;not null" json:"order_date"`
	UserID          int32     `gorm:"column:user_id;not null" json:"user_id"`
	BookIds         string    `gorm:"column:book_ids;not null" json:"book_ids"`
	OrderAmount     int32     `gorm:"column:order_amount;not null" json:"order_amount"`
	OrderMoney      float64   `gorm:"column:order_money;not null" json:"order_money"`
	DeliveryAddress string    `gorm:"column:delivery_address;not null" json:"delivery_address"`
	DeliveryStatus  string    `gorm:"column:delivery_status;not null" json:"delivery_status"`
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
