// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOutOfStockRecord = "out_of_stock_record"

// OutOfStockRecord mapped from table <out_of_stock_record>
type OutOfStockRecord struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BookID    int32     `gorm:"column:book_id;not null" json:"book_id"`
	Number    int32     `gorm:"column:number;not null" json:"number"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName OutOfStockRecord's table name
func (*OutOfStockRecord) TableName() string {
	return TableNameOutOfStockRecord
}
