// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePurchaseOrder = "purchase_order"

// PurchaseOrder mapped from table <purchase_order>
type PurchaseOrder struct {
	ID                 int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OutOfStockRecordID int32     `gorm:"column:out_of_stock_record_id;not null" json:"out_of_stock_record_id"`
	Number             int32     `gorm:"column:number;not null" json:"number"`
	Status             string    `gorm:"column:status;not null" json:"status"`
	CreatedAt          time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt          time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName PurchaseOrder's table name
func (*PurchaseOrder) TableName() string {
	return TableNamePurchaseOrder
}
