// Code generated by hertz generator.

package main

import (
	handler "db_lab_library/biz/handler"
	"db_lab_library/biz/handler/book"
	"db_lab_library/biz/handler/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	bookController := r.Group("book")
	{
		bookController.POST("", book.Insert)
	}

	userController := r.Group("user")
	{
		userController.POST("", user.Insert)
	}
}
